### ISSUE TITLE
When running test, java.nio.file.FileSystemException: .: Too many open files

### ISSUE THREAD

**Issue by Anilople** [Anilople/javajvm#6]
# Too many open files

Different machine will get differenct result.

But in [travis-ci](https://travis-ci.com/), it happened.

Cause by using too many times `java.nio.file.Files.newDirectoryStream` indirectly.

stackoverflow link
[java-nio-file-filesystemexception-proc-too-many-open-files](https://stackoverflow.com/questions/26334421/java-nio-file-filesystemexception-proc-too-many-open-files)

Stack trace like follow:

```java
java.nio.file.FileSystemException: .: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:427)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.Files.list(Files.java:3451)
	at com.github.anilople.javajvm.utils.ClassContextUtils.getAllPathNested(ClassContextUtils.java:90)
	at com.github.anilople.javajvm.utils.ClassContextUtils.getAllPathNested(ClassContextUtils.java:80)
	at com.github.anilople.javajvm.classpath.Classpath.<init>(Classpath.java:70)
	at com.github.anilople.javajvm.JavaJvmApplication.<init>(JavaJvmApplication.java:35)
	at com.github.anilople.javajvm.JavaJvmApplication.main(JavaJvmApplication.java:57)
	at com.github.anilople.javajvm.testcode.Sum1To100Test.mainTest(Sum1To100Test.java:12)
```

`utils.ClassContextUtils.getAllPathNested` -> `java.nio.file.Files.list` -> `java.nio.file.Files.newDirectoryStream`

**Comment by Anilople** [comment]
#8 pull request solve this issue
